version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mkdata
      POSTGRES_PASSWORD: mkdata
      POSTGRES_DB: mkdataapi

volumes:
  db_data: